extensions:
  health_check: { endpoint: "0.0.0.0:13133" }

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch: {}

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls: { insecure: true }

  prometheus:
    endpoint: "0.0.0.0:8880"

  # Logs → Loki (native OTLP HTTP)
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    compression: gzip
    tls:
      insecure: true

  # Traces → Tempo (OTLP gRPC)
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: info
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, prometheus]
